# Generated by Django 6.0.3 on 2026-03-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='我的个人主页', max_length=50)),
                ('bio', models.TextField(default='这是一段关于我的介绍。在这里你可以记录心情，留下印记。欢迎大家留言互动！')),
            ],
        ),
    ]
