# Generated by Django 6.0.3 on 2026-03-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_message_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='announcement',
            field=models.TextField(default='欢迎来到 bianra 的小屋！\n这里是一个自由留言的空间。\n点击头像可以编辑主页信息。'),
        ),
    ]
